"""Measure stable traveler locomotion pivots without changing any PNG pixels.

The action atlas's original pivots follow the lowest silhouette (sometimes a
sword tip or a single forward foot). Register walk poses against the idle head
instead, preserving the idle/attack origin, body scale and vertical grounding.
Run from the repository root with Pillow installed.
"""
import hashlib
import json
from pathlib import Path

from PIL import Image

ART = Path(__file__).resolve().parents[2] / "assets/generated/action"
SHEETS = ["wanderer", "saber", "moonward", "moonward_saber"]


def head_center(image, box):
    x, y, width, height = box[:4]
    pixels = [xx - x for yy in range(y + int(height * 0.08), y + int(height * 0.25))
              for xx in range(x, x + width) if image.getpixel((xx, yy))[3] >= 100]
    assert pixels, "Empty head measurement"
    return sum(pixels) / len(pixels)


def main():
    regions = json.loads((ART / "regions.gd").read_text().split("const DATA: Dictionary = ", 1)[1])
    result = {}
    for sheet in SHEETS:
        path = ART / f"{sheet}.png"
        image = Image.open(path).convert("RGBA")
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        assert digest == regions[sheet]["sha256"], f"Stale source regions: {sheet}"
        anchors = []
        for facing in range(4):
            poses = regions[sheet]["frames"][facing * 12:facing * 12 + 3]
            idle_offset = head_center(image, poses[0]) - poses[0][4]
            anchors.append([round(head_center(image, box) - idle_offset, 4) for box in poses])
        result[sheet] = {"sha256": digest, "anchors": anchors}
    (ART / "armed_walk_anchors.gd").write_text(
        "extends RefCounted\n## Generated by tools/art/build_armed_walk_anchors.py; PNGs are unchanged.\n"
        "## Per facing: idle, walk_a, walk_b. All other poses keep original anchors.\n"
        "const DATA: Dictionary = " + json.dumps(result, indent=2) + "\n")
    print("Measured stable armed-walk pivots: four traveler outfits, four facings")


if __name__ == "__main__":
    main()
